# Main Application Settings for NexusMind
app:
  name: "NexusMind"
  version: "0.1.0" # Should ideally match pyproject.toml
  host: "0.0.0.0"
  port: 8000 # Default port for Uvicorn
  log_level: "INFO" # Default log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  # debug: false # Set to true for development if needed, enables more verbose errors

# NexusMind Core Parameters
asr_got:
  default_parameters:
    # Parameters for Stage 1: Initialization
    initial_confidence: [0.9, 0.9, 0.9, 0.9] # P1.5 via P1.1
    initial_layer: "root_layer"             # P1.1

    # Parameters for Stage 2: Decomposition
    default_decomposition_dimensions:       # P1.2
      - label: "Scope and Delimitations"
        description: "Clearly define the boundaries and specific focus of the research question."
      - label: "Core Objectives"
        description: "Identify the primary goals and desired outcomes of the analysis."
      - label: "Methodological Approach"
        description: "Outline the research methods and analytical techniques to be employed."
      - label: "Data Requirements and Availability"
        description: "Specify the types of data needed and assess their accessibility and quality."
      - label: "Key Assumptions"
        description: "List any underlying assumptions made at the outset of the investigation."
      - label: "Potential Challenges and Limitations"
        description: "Anticipate obstacles, constraints, or limitations that might affect the research."
      - label: "Expected Impact and Applications"
        description: "Consider the potential significance of the findings and their practical use cases."
      - label: "Ethical Considerations"
        description: "Address any ethical implications related to the research topic or methodology."
      - label: "Identification of Knowledge Gaps" # P1.15 via P1.2
        description: "Pinpoint areas of uncertainty or missing information relevant to the query."
      - label: "Assessment of Potential Biases" # P1.17 via P1.2
        description: "Identify possible cognitive, methodological, or data-related biases."
    dimension_confidence: [0.8, 0.8, 0.8, 0.8] # P1.2

    # Parameters for Stage 3: Hypothesis/Planning
    hypotheses_per_dimension: # k from P1.3
      min: 2
      max: 4
    hypothesis_confidence: [0.5, 0.5, 0.5, 0.5] # P1.3
    default_disciplinary_tags: # P1.8 (initial tagging)
      - "general_science"
      - "interdisciplinary_studies"
    # Default plan types for hypotheses (can be expanded)
    default_plan_types: ["literature_review", "data_analysis", "simulation", "expert_consultation"]


    # Parameters for Stage 4: Evidence Integration
    evidence_max_iterations: 5                # P1.4
    # Bayesian update parameters can be more detailed here if needed (P1.14)

    # Parameters for Stage 5: Pruning/Merging
    pruning_confidence_threshold: 0.2         # min(E[C]) from P1.5
    pruning_impact_threshold: 0.3             # P1.5 considering P1.28
    merging_semantic_overlap_threshold: 0.8   # P1.5

    # Parameters for Stage 6: Subgraph Extraction (P1.6)
    subgraph_min_confidence_threshold: 0.6
    subgraph_min_impact_threshold: 0.5
    # temporal_recency_days: 365 # Example: only consider nodes/evidence from the last year

    # Parameters for Stage 8: Reflection (P1.7)
    # Thresholds for audit checks, e.g., high_confidence_coverage_min: 0.3

  # Multi-layer network configuration (P1.23)
  # Define layers that hypotheses or other elements can belong to.
  # This is a global definition; specific node assignments happen during graph construction.
  layers:
    root_layer:
      description: "Core foundational layer for initial task understanding and decomposition."
    evidence_layer:
      description: "Layer primarily containing evidence nodes and their direct connections."
    hypothesis_analysis_layer:
      description: "Layer focused on hypothesis development, competition, and refinement."
    integration_synthesis_layer:
      description: "Layer for integrating diverse findings and synthesizing overall conclusions."
    # Add more domain-specific layers as needed, e.g.:
    # "immunology_perspective":
    #   description: "Nodes and analyses related to immunological aspects."
    # "molecular_perspective":
    #   description: "Nodes and analyses related to molecular biology aspects."

# Configuration for Model Context Protocol (MCP) Server behavior
mcp_settings:
  protocol_version: "2024-11-05" # As per original claude_desktop_config.json  server_name: "NexusMind MCP Server"
  server_version: "0.1.0" # Match app.version
  vendor_name: "Your Organization" # Change this
  # display_name: "NexusMind" # If needed by MCP client
  # description: "NexusMind provides advanced scientific reasoning capabilities." # If needed

# Optional: Direct Claude API integration settings (if the app needs to call Claude API itself)
# claude_api:
#   api_key: "env_var:CLAUDE_API_KEY" # Example: Load from environment variable CLAUDE_API_KEY
#   default_model: "claude-3-opus-20240229"
#   timeout_seconds: 120
#   max_retries: 2

# Example of how to structure a list of predefined knowledge domains or disciplines
# These could be used for tagging, IBN detection, etc. (Ref P1.8)
knowledge_domains:
  - name: "Skin Immunology"
    keywords: ["skin", "immune", "immunology", "dermatitis", "psoriasis"]
    description: "Focuses on the immune responses and mechanisms within the skin."
  - name: "Dermatology"
    keywords: ["dermatology", "skin diseases", "cutaneous"]
    description: "Branch of medicine dealing with the skin, hair, nails, and their diseases."
  - name: "Cutaneous Malignancies"
    keywords: ["skin cancer", "melanoma", "lymphoma", "carcinoma"]
    description: "Cancers arising from the skin."
  - name: "CTCL (Cutaneous T-Cell Lymphoma)"
    keywords: ["ctcl", "mycosis fungoides", "sezary syndrome"]
    description: "A rare type of non-Hodgkin lymphoma that affects the skin."
  - name: "Genomics"
    keywords: ["genomics", "gene expression", "dna", "rna", "sequencing"]
    description: "Study of genomes, their structure, function, evolution, and mapping."
  - name: "Microbiome"
    keywords: ["microbiome", "microbiota", "bacteria", "fungi", "virome"]
    description: "The community of microorganisms living together in a particular habitat, including the human body."
  - name: "Molecular Biology"
    keywords: ["molecular biology", "proteins", "enzymes", "pathways"]
    description: "Branch of biology that seeks to understand the molecular basis of biological activity."
  - name: "Machine Learning"
    keywords: ["machine learning", "ai", "neural networks", "deep learning", "prediction"]
    description: "Field of artificial intelligence that uses statistical techniques to give computer systems the ability to 'learn'."
  - name: "Biomedical LLMs"
    keywords: ["biomedical llm", "medical ai", "nlp in medicine"]
    description: "Large language models specialized for biomedical applications."
  # Add more domains based on Dr. Dey's profile (K3.3, K3.4) or general needs